# Day3 データの整理 - NumPy

# 外部ライブラリの使い方

In [1]:
#timeモジュールをインポート
import time
#1〜3まで繰り返す。
for count in range(1,4): 
    #1秒止まる
    time.sleep(1) 
     #経過秒数を出力
    print("{}秒経過".format(count))

1秒経過
2秒経過
3秒経過


## 外部ライブラリ 演習

In [2]:
# 問題１

In [ ]:
import time 
#1〜30まで繰り返す
for count in range(1,31): 
    #カウントが３の倍数かどうかを判定する
    if count%3==0: 
        print("python最高!")
    else :
        print("{}秒経過".format(count)) 
    time.sleep(1)

1秒経過
2秒経過
python最高!
4秒経過
5秒経過
python最高!
7秒経過
8秒経過
python最高!
10秒経過
11秒経過
python最高!
13秒経過
14秒経過
python最高!
16秒経過
17秒経過
python最高!
19秒経過
20秒経過
python最高!
22秒経過
23秒経過
python最高!


# Numpyで配列を高速に処理しよう

## NumPy配列の作り方

In [2]:
#Numpyのインポート
import numpy as np 

In [ ]:
#1次元の配列生成

#正
a = np.array([1, 2, 3]) 
#誤：エラーを生む
#a = np.array(1, 2, 3) 

In [ ]:
#２次元の配列生成

# 正
a = np.array([[1, 2, 3],
              [4, 5, 6]]) 

# 誤：エラーを生む
#a = np.array([1, 2, 3],
 #                 [4, 5, 6]) 

In [ ]:
# ゼロ行列
zeros2x3 = np.zeros((2, 3))
zeros2x3

In [ ]:
# イチ行列
ones2x3 = np.ones((2,3))
ones2x3

In [ ]:
# 0から始まる連続する10の整数の配列
print(np.arange(10))

#np.arange(始, 終, 間隔)
print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3))

#等間隔な数列を生成(始, 終, 個数)
print(np.linspace(0, np.pi, 10))

In [ ]:
#6要素の配列を生成
array = np.array([1, 2, 3, 4, 5, 6])

#arrayを2x3行列に整形
arr2x3 = array.reshape(2, 3)

#! 割り切れない数字ではreshape不可
#arr4x2 = array.reshape(2, 4)

In [ ]:
#行列を1次元に"ほどく "
a = arr2x3.ravel() 

In [ ]:
#転置行列
a2x3_T = arr2x3.T
#transpose関数でも同様
arr2x3_transpose=arr2x3.transpose()

In [ ]:
arr2x3 = array.reshape(2, 3)
arr2x3

In [ ]:
arr2x3.reshape(3,2)

In [ ]:
arr2x3.transpose()

## NumPy配列の作り方 演習　問題１〜３

In [3]:
# 0 〜 １4が入った配列を作成
a = np.arange(15)
print(a)

# aを３行５列に整形
b = a.reshape(3,5)
print(b)

print(a.shape)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(15,)
(3, 5)


## NumPy配列に対する数学的な演算

In [ ]:
a = np.array([0, 1, 2, 3, 9])
b = np.array([2, 4, 6, 0 , np.inf])
#足し算(+, np.add(a, b))
a+b
a+3
#引き算(-, np.subtract(a, b))
a-b
a-3

In [ ]:
#掛け算(*, np.multiply(a, b) )
print(f"a * b: {a * b}")
#累乗(**, np.power(a, b) )
print(f"a ** b: {a ** b}")
#平方根(np.sqrt(a), np.power(a, 1/2) )
print(f"np.sqrt(a): {np.sqrt(a)}")

In [ ]:
#割り算(/, np.divide(a, b) )
print(f"a / b: {a / b}")
#商の整数部分(//)
print(f"100 // b: {a // b}")
#剰余(%,np.mod() )
print(f"100%b: {100 % b}")

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#同じ要素番号同士の掛け算
print(A * B)
#行列の掛け算 (np.dot(A,B)でも可 )
print(A.dot(B))

In [ ]:
#統計的な計算をしよう

In [ ]:
a = np.array([1,2,3,4,5])
print(a.mean()) # 平均値

In [ ]:
print(f"a: {a}")
print(f"sum: {a.sum()}") # 和
print(f"min: {a.min()}") #最小値
print(f"max: {a.max()}") #最大値
print(f"aの平均は{a.mean()},標準偏差は{a.std():.3f}です.")

In [ ]:
b=np.arange(1,13,2).reshape(2,3)
#列ごとの和
print(b.sum(axis=0))
#行中の最小値
print(b.min(axis=1))
#各行までの累積和
print(b.cumsum(axis=0))

## 補足

In [ ]:
#三角関数
np.sin(np.pi)
np.cos(np.pi)
np.tan(np.pi) 

#逆三角関数
np.arcsin(1)
np.arccos(1)
np.arctan(1) 

#指数関数
np.exp(0)

#対数関数
np.log(1)
np.log10(1)

#絶対値
np.abs(1);

#円周率
np.pi

## NumPy配列に対する数学的な演算 演習

In [ ]:
# 1〜10までの配列を生成し変数aに代入
a=np.arange(1,11)
a

In [ ]:
#aの一次元配列を2行5列行列に変換
b=a.reshape(2,5)
b

In [ ]:
#1〜5の一次元配列を生成
b0=np.arange(1,6)
# 6〜10の一次元配列を生成
b1=np.arange(6,11)
#配列の要素同士の演算
print(b0+b1)
print(b0-b1)
#要素間の割り算の余りを出す
print(b0%b1)
#要素間の割り算の商を出す
print(b0/b1)

## 配列内部のデータ参照

In [ ]:
#適当な配列を用意する
a = np.array(list("あいうえお"))
#スライス
a[[0,2]]#["あ","う"]

In [ ]:
print(a[1:4])#["い","う","え"]
print(a[0:4:2])

In [ ]:
b=np.array([[1,2,3],[4,5,6]])

In [ ]:
b[1,2]#1行2列目を取り出す

In [ ]:
b[:,2]#2列目を取り出す

In [ ]:
b[:,[0,2]]#0列目と2列目

In [ ]:
# 0〜24の一次元配列を生成し、5次正方行列に変換
b = np.arange(25).reshape(5, 5)

#3列目の要素すべて
print(b[:,3] )
#2行3列目の要素
print(b[2,3] )

In [ ]:
#(1, 3)行と(1, 3)列が交わる
#2x2=4通りの組み合わせ
b[1:4:2, 1:4:2]  

In [ ]:
#対角成分の表示(行列番号が同じ成分)
b[range(5),range(5)]

#最終要素に存在する配列を取り出す
#この例はb[-1,:]と等価
b[-1] 

In [ ]:
#4x5の配列の生成
a = np.arange(20).reshape((4,5))

In [ ]:
#aの要素が3の倍数であれば1, そうでなければ0をかえす
b = np.where((a>0)&(a%3 == 0), 1, 0)
b

## 配列内部のデータ参照 演習

In [ ]:
array_1 = np.arange(1, 26).reshape(5, 5)
print(array_1)

In [ ]:
#(1,2)行, (1,2)列の交点を出力
print(array_1[1:3,1:3])